In [1]:
1+2

3

In [3]:
print("julia")

julia

In [4]:
println("julia")

julia


In [5]:
power = (2 ^ 2)
power

4

In [6]:
"julia"

"julia"

In [7]:
"""julia"""

"julia"

In [8]:
""julia""

LoadError: syntax: cannot juxtapose string literal

In [9]:
"this is "julia" lang"

LoadError: syntax: cannot juxtapose string literal

In [10]:
"""this is "julia" lang"""

"this is \"julia\" lang"

In [12]:
a = 'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [13]:
typeof(a)

Char

In [22]:
name = "Shivam"
fingre = 10
leg_fing = 10
print("$name has $fingre and $leg_fing \n")
print(name , " has " , fingre , " and " , leg_fing)

Shivam has 10 and 10 
Shivam has 10 and 10

In [21]:
print("His name is", " Shivam")
string("His name is", " Shivam")

His name is Shivam

"His name is Shivam"

In [23]:
s1 = "Hello, "
s2 = "how are you"

"how are you"

In [24]:
s1 * s2

"Hello, how are you"

In [25]:
"$s1$s2"

"Hello, how are you"

In [26]:
phonebook = Dict("Shivam" => "123321", "Choudhary" => "098997")

Dict{String,String} with 2 entries:
  "Choudhary" => "098997"
  "Shivam"    => "123321"

In [27]:
phonebook["Germy"] = "7565667"

"7565667"

In [28]:
phonebook

Dict{String,String} with 3 entries:
  "Choudhary" => "098997"
  "Shivam"    => "123321"
  "Germy"     => "7565667"

In [29]:
phonebook["Shivam"]

"123321"

In [30]:
pop!(phonebook, "Germy")

"7565667"

In [31]:
phonebook

Dict{String,String} with 2 entries:
  "Choudhary" => "098997"
  "Shivam"    => "123321"

In [32]:
animals = ("Lion", "Tiger", "Cat", "Dog")

("Lion", "Tiger", "Cat", "Dog")

In [33]:
animals[1]

"Lion"

In [34]:
animal = ["Lion", "Tiger", "Cat", "Dog"]

4-element Array{String,1}:
 "Lion"
 "Tiger"
 "Cat"
 "Dog"

In [36]:
number = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [37]:
any = [1, "helloo", 1.1]

3-element Array{Any,1}:
 1
  "helloo"
 1.1

In [38]:
any[1]

1

In [39]:
animal[2]

"Tiger"

In [40]:
animal[2] = "Big Tiger"

"Big Tiger"

In [41]:
animal

4-element Array{String,1}:
 "Lion"
 "Big Tiger"
 "Cat"
 "Dog"

In [42]:
push!(animal, "Fish")

5-element Array{String,1}:
 "Lion"
 "Big Tiger"
 "Cat"
 "Dog"
 "Fish"

In [44]:
pop!(animal)

"Fish"

In [45]:
animal

4-element Array{String,1}:
 "Lion"
 "Big Tiger"
 "Cat"
 "Dog"

In [46]:
rand(4, 3)

4×3 Array{Float64,2}:
 0.213312  0.128671   0.52404
 0.119591  0.0971632  0.568404
 0.325153  0.949989   0.339356
 0.870575  0.115795   0.794926

In [47]:
rand(4, 3, 2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.384031  0.934179  0.597261
 0.917258  0.910834  0.640275
 0.795005  0.242919  0.0460171
 0.122211  0.217811  0.895702

[:, :, 2] =
 0.573659  0.377753  0.762013
 0.204951  0.630498  0.665272
 0.151699  0.983008  0.668197
 0.86428   0.731571  0.56972

In [48]:
n = 0
while n < 10
    n += 1
    print(n)
end 

12345678910

In [53]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [54]:
m, n = 5, 5
A = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [55]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end

In [56]:
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [59]:
m, n = 5, 5
B = zeros(m, n)
for i in 1:m, j in 1:n
    B[i, j] = i + j
end

In [60]:
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0